# fly.toml app configuration file generated for my-private-plane on 2023-04-20T08:43:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-private-plane"
primary_region = "lax"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
